// <auto-generated />
using System;
using LoL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoL.Migrations
{
    [DbContext(typeof(LoLDbContext))]
    partial class LoLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoL.Models.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Legend1Id")
                        .HasColumnType("int");

                    b.Property<int>("Legend2Id")
                        .HasColumnType("int");

                    b.Property<int>("Legend3Id")
                        .HasColumnType("int");

                    b.Property<int>("Legend4Id")
                        .HasColumnType("int");

                    b.Property<int>("Legend5Id")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Legend1Id");

                    b.HasIndex("Legend2Id");

                    b.HasIndex("Legend3Id");

                    b.HasIndex("Legend4Id");

                    b.HasIndex("Legend5Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Compositions");
                });

            modelBuilder.Entity("LoL.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Composition1Id")
                        .HasColumnType("int");

                    b.Property<int>("Composition2Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Winner")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Composition1Id")
                        .IsUnique();

                    b.HasIndex("Composition2Id")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LoL.Models.Legend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Legends");
                });

            modelBuilder.Entity("LoL.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LoL.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Player3Id")
                        .HasColumnType("int");

                    b.Property<int>("Player4Id")
                        .HasColumnType("int");

                    b.Property<int>("Player5Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id")
                        .IsUnique();

                    b.HasIndex("Player2Id")
                        .IsUnique();

                    b.HasIndex("Player3Id")
                        .IsUnique();

                    b.HasIndex("Player4Id")
                        .IsUnique();

                    b.HasIndex("Player5Id")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LoL.Models.Composition", b =>
                {
                    b.HasOne("LoL.Models.Legend", "Legend1")
                        .WithMany()
                        .HasForeignKey("Legend1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Legend", "Legend2")
                        .WithMany()
                        .HasForeignKey("Legend2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Legend", "Legend3")
                        .WithMany()
                        .HasForeignKey("Legend3Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Legend", "Legend4")
                        .WithMany()
                        .HasForeignKey("Legend4Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Legend", "Legend5")
                        .WithMany()
                        .HasForeignKey("Legend5Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Legend1");

                    b.Navigation("Legend2");

                    b.Navigation("Legend3");

                    b.Navigation("Legend4");

                    b.Navigation("Legend5");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LoL.Models.Game", b =>
                {
                    b.HasOne("LoL.Models.Composition", "Composition1")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Game", "Composition1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Composition", "Composition2")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Game", "Composition2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Composition1");

                    b.Navigation("Composition2");
                });

            modelBuilder.Entity("LoL.Models.Team", b =>
                {
                    b.HasOne("LoL.Models.Player", "Player1")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Team", "Player1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Player", "Player2")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Team", "Player2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Player", "Player3")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Team", "Player3Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Player", "Player4")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Team", "Player4Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoL.Models.Player", "Player5")
                        .WithOne()
                        .HasForeignKey("LoL.Models.Team", "Player5Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Player3");

                    b.Navigation("Player4");

                    b.Navigation("Player5");
                });
#pragma warning restore 612, 618
        }
    }
}
